name: Private release
on:
  push:
    tags: ['v*.*.*']
permissions:
  contents: read
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Validate tagged sources
        run: make check schema
      - run: git diff --exit-code -- provider/cmd/pulumi-resource-tplink/schema.json
      - name: Build and publish private binaries
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make release
